


header_pages:  
  - Intro.md
  - case-studies.md
  - Faq.md


markdown: kramdown
title: Winternship 2025
email: sudarshan@iitrpr.ac.in
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /winternship/ # the subpath of your site, e.g. /blog
url: https://sudarshansudarshan.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sudarshaniisc
github_username:  sudarshansudarshan

# Build settings
theme: minima
plugins:
  - jekyll-feed

timezone: Asia/Kolkata

collections:
  case_studies:
    output: true
    permalink: /case-studies/:slug/

